### ISSUE TITLE
Create a menu that has different types of animals

### ISSUE THREAD

**Issue by phllpbll189** [CSI-280/team1#17]

**Comment by NathanDiMauro** [comment]
@phllpbll189 try to remember to put the correct label on when your create issues

**Comment by phllpbll189** [comment]
Okay, ill pay closer attention to that.

**Comment by phllpbll189** [comment]
So starting work on the page that has the list of pets, i named it pets. Will this have conflict with anyone elses current work?

**Comment by phllpbll189** [comment]
So far I have created a button next to the home and about buttons that is simply labeled pets

**Comment by NathanDiMauro** [comment]
@phllpbll189 yes. A page named pets already exists in the project. You need to pull the master branch to get the most recent build of the project. `git pull origin master`

**Comment by phllpbll189** [comment]
Okay thanks, ill do that and see if i can add something to that idea.

**Comment by phllpbll189** [comment]
@NathanDiMauro so I'm trying to git pull after I made my changes. Since you've already been working on the pets page and I'm assuming a button to get there, I had decided to discard my changes and switch to master. When I use git pull origin master it aborts because of the previous changes to my branch. I even use git pull origin master -f (to force) and it still aborts. Any suggestions?

**Comment by phllpbll189** [comment]
P.S. I had already used git restore on the changed files as well.

**Comment by phllpbll189** [comment]
Nevermind I got it to work by stashing the changes. On a side note. Should I create issues for personal issues I'm having trouble with or is there a way to close comments to indicate I fixed it?

**Comment by NathanDiMauro** [comment]
The issues should just be the is stuff we are working on for class. Using the comments for smaller sub-issues like you have been is perfect.

**Comment by chrisbendel** [comment]
> @NathanDiMauro so I'm trying to git pull after I made my changes. Since you've already been working on the pets page and I'm assuming a button to get there, I had decided to discard my changes and switch to master. When I use git pull origin master it aborts because of the previous changes to my branch. I even use git pull origin master -f (to force) and it still aborts. Any suggestions?

@phllpbll189 in the future, instead of discarding your changes, you can add and commit your changes on your branch, then pull like @NathanDiMauro suggested, that should result in master being merged into your branch (you may have merge conflicts to resolve, but that's normal)
