### ISSUE TITLE
Add a fake sign up page

### ISSUE THREAD

**Issue by phllpbll189** [CSI-280/team1#27]
A simple username password text box. Hopefully get it to show your username as you browse after.

**Comment by phllpbll189** [comment]
For some reason, I can't open any of the files pertaining to the code and it's failing to compile. Does anyone know about this issue?

` i ｢wds｣: Project is running at http://0.0.0.0:3000/`
`i ｢wds｣: webpack output is served from /`
`i ｢wds｣: Content not from webpack is served from C:\Users\phllp\team1\public`
`i ｢wds｣: 404s will fallback to /index.html`
`Starting the development server...`

`Failed to compile.`

`./src/components/pf.js`
` Module not found: Can't resolve '@petfinder/petfinder-js' in 'C:\Users\phllp\team1\src\components' `
` Compiling... `
` Failed to compile. `

This is what Git Bash is outputting.

**Comment by chrisbendel** [comment]
https://github.com/petfinder-com/petfinder-js-sdk
